name: "FFRegions"
version: 0.0.1
main: com.kliminskyi.ffregions.FFRegions
api-version: "1.16"
commands:
  ffrg:
    description: View or edit regions from FFRegions
    usage: /<command> <subcommand>
